# Generated by Django 5.0.6 on 2025-01-22 12:04

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('address', models.TextField(blank=True)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1)),
                ('mobile', models.CharField(blank=True, max_length=11)),
                ('base_salary', models.DecimalField(decimal_places=2, max_digits=10)),
                ('section', models.CharField(choices=[('Billing Section', 'Billing Section'), ('Men’s Nicker', 'Men’s Nicker'), ('Bag Section', 'Bag Section'), ('Saree section', 'Saree section'), ('Shirting and Suiting', 'Shirting and Suiting'), ('Men’s Readymade', 'Men’s Readymade'), ('Parakar', 'Parakar'), ('Ladies Undergarments', 'Ladies Undergarments'), ('Blouse Pc Section', 'Blouse Pc Section'), ('TOP section', 'TOP section'), ('Chudi Section', 'Chudi Section'), ('Kids Section', 'Kids Section'), ('Towel Section', 'Towel Section')], max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('morning_check_in_time', models.DateTimeField(blank=True, null=True)),
                ('morning_check_out_time', models.DateTimeField(blank=True, null=True)),
                ('lunch_check_in_time', models.DateTimeField(blank=True, null=True)),
                ('lunch_check_out_time', models.DateTimeField(blank=True, null=True)),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='emp.employee')),
            ],
        ),
        migrations.CreateModel(
            name='AdvancePayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('is_paid', models.BooleanField(default=False)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='emp.employee')),
            ],
        ),
    ]
