# Generated by Django 5.0.6 on 2025-01-17 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='section',
            field=models.CharField(choices=[('Billing Section', 'Billing Section'), ('Men’s Nicker', 'Men’s Nicker'), ('Bag Section', 'Bag Section'), ('Saree section', 'Saree section'), ('Shirting and Suiting', 'Shirting and Suiting'), ('Men’s Readymade', 'Men’s Readymade'), ('Parakar', 'Parakar'), ('Ladies Undergarments', 'Ladies Undergarments'), ('Blouse Pc Section', 'Blouse Pc Section'), ('TOP section', 'TOP section'), ('Chudi Section', 'Chudi Section'), ('Kids Section', 'Kids Section'), ('Towel Section', 'Towel Section')], default='Billing Section', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='employee',
            name='address',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='mobile',
            field=models.CharField(blank=True, max_length=11, unique=True),
        ),
    ]
