# Generated by Django 5.0.6 on 2025-01-17 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emp', '0002_employee_section_alter_employee_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='mobile',
            field=models.CharField(blank=True, max_length=11),
        ),
    ]
